version: "3"
 volumes:
   nextcloud:
   nc_db:
   nc_ata:
 services:
   db:
     image: mariadb
     command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
     restart: always
     volumes:
       - nc_db:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=1234osradar
       - MYSQL_PASSWORD=1234osradar
       - MYSQL_DATABASE=nextclouddb
       - MYSQL_USER=nextclouduser
 app:
     image: nextcloud
     ports:
       - 8090:80
     links:
       - db
     volumes:
       - nextcloud:/var/www/html
       - nc_data:/var/www/html/data
     restart: always



# ## NOTES

# GIT LOCATION - https://github.com/Neu-Bob/nextcloud